export const PLANS = {
  starter: {
    id: 'starter',
    name: 'Starter',
    price: 149,
    interval: 'month',
    description: 'Perfect for small crews getting started',
    features: [
      'Up to 5 operators',
      'Schedule board & dispatch',
      'Job tracking & timecards',
      'PDF invoices & dispatch tickets',
      'Customer portal & signatures',
      'Email notifications',
    ],
    cta: 'Start Free Trial',
    highlighted: false,
    priceId: process.env.STRIPE_STARTER_PRICE_ID!,
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    price: 299,
    interval: 'month',
    description: 'For growing operations teams',
    features: [
      'Up to 20 operators',
      'Everything in Starter',
      'NFC time clock system',
      'Job scope & progress tracking',
      'Facilities & badge management',
      'QuickBooks CSV export',
      'Analytics & commission tracking',
      'Priority support',
    ],
    cta: 'Start Free Trial',
    highlighted: true,
    priceId: process.env.STRIPE_PROFESSIONAL_PRICE_ID!,
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise',
    price: 599,
    interval: 'month',
    description: 'For large multi-crew operations',
    features: [
      'Unlimited operators',
      'Everything in Professional',
      'White-label branding',
      'Custom domain',
      'Dedicated account manager',
      'Custom integrations',
      'SLA guarantee',
      'Onboarding & training',
    ],
    cta: 'Contact Sales',
    highlighted: false,
    priceId: process.env.STRIPE_ENTERPRISE_PRICE_ID!,
  },
} as const;

export type PlanId = keyof typeof PLANS;
